 <h1>Evidence pojištěnců</h1> 
 
<table>
 <thead>    
    <tr><th>Jméno</th><th>Příjmení</th><th>Věk</th><th>Tel. číslo</th><?php if ($admin) : ?><th colspan="2">Administrace</th><?php endif ?>
    </tr>   
 </thead>
 <tbody>
   <?php foreach ($pojistenci as $pojistenec) : ?>                                                                  
    <tr><td><?=$pojistenec['jmeno']?></td><td><?=$pojistenec['prijmeni']?></td><td><?=$pojistenec['vek']?></td>
        <td><?=$pojistenec['tel_cislo']?></td>
        
      <?php if ($admin) : ?><td><a href="editace/<?= $pojistenec['pojistenec_id'] ?>">Editovat</a></td>
                        <td><a href="pojistenec/<?= $pojistenec['pojistenec_id'] ?>/odstranit">Odstranit</a></td>
      <?php endif ?>
      
    </tr>
   <?php endforeach ?>                    
 </tbody>   
</table> 
